plugins {
    id "com.android.application"
}

android {
    namespace "org.oylama.app"
    compileSdk 34

    defaultConfig {
        applicationId "org.oylama.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/oylama-release.jks")
            storePassword "oylama-demo"
            keyAlias "oylama"
            keyPassword "oylama-demo"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ["META-INF/versions/9/OSGI-INF/MANIFEST.MF", "META-INF/DEPENDENCIES", "META-INF/LICENSE*", "META-INF/NOTICE*"]
        }
    }
}

dependencies {
    implementation "org.bouncycastle:bcprov-jdk18on:1.80"
}
